FROM quay.io/prashantdawar/debian-containers:buster

LABEL maintainer="prashantdawar.2008@gmail.com"
RUN apt update && \
    apt upgrade -y && \
    apt install -y apache2 && \
    apt clean



EXPOSE 8080
# RUN service apache2 start
CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]