FROM docker.io/library/debian:buster

LABEL maintainer="prashantdawar.2008@gmail.com"
RUN apt update && \
    apt upgrade -y && \
    apt install htop curl wget nload vnstat vim nano && \
    apt clean